export const DASHBOARD_DATE_FORMAT = 'YYYY-MM-DD';

export const ACTIVE_PLAYERS_UPDATE_INTERVAL = 300000;

export const CURRENT_ACTIVES_UPDATE_INTERVAL = 300000;

export const ACTIVE_SESSIONS_BREAKDOWN_UPDATE_INTERVAL = 60000;

export const ACTIVE_AND_NEW_PLAYERS_UPDATE_INTERVAL = 900000;

export const BETTING_ACTIVITY_UPDATE_INTERVAL = 900000;

export const TOP_WINNERS_AND_LOSERS_UPDATE_INTERVAL = 600000;

export const WAIT_TIME_UPDATE_INTERVAL = 60000;

export const MACHINES_AVAILABILITY_UPDATE_INTERVAL = 60000;

export const MACHINE_STATUS_UPDATE_INTERVAL = 60000;

export const LATEST_ALERTS_UPDATE_INTERVAL = 300000;
